### ISSUE TITLE
Source des valeurs des tranches

### ISSUE THREAD

**Issue by blaiseli** [Insoumis/declarachon#3]
Bonjour,

Avez-vous des nouvelles des limites et des taux des 14 tranches ? J'aurais aimé faire une comparaison des courbes de revenu après impôt en fonction du revenu avant impôts dans le système actuel et dans le système Avenir en commun.

Je vois que votre code source utilise des valeurs inventées.

**Comment by HugoHeneault** [comment]
Salut @blaiseli 

Malheureusement, pour le moment nous n'avons pas ces données là. 
Le mieux est de se rapprocher des auteurs du livret sur la fiscalité :)

**Comment by blaiseli** [comment]
Je leur ai écrit, mais n'ai pas encore de réponses. Par contre, j'ai trouvé ceci:
https://github.com/jlm2017/impotsoumis/blob/master/impotsoumis/src/data/legislative_parameters/NewIR.js
Ça n'est pas une info officielle, mais ça peut servir de base d'exploration.
